on:
  push:
    tags:
      - '*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK 12
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11.0.4'
          java-package: 'jdk'
      - run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Assemble Jar
        run: ./gradlew assembleShadowDist
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Automatic release.
          draft: false
          prerelease: false
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./build/libs/JukeBot.jar
            asset_name: JukeBot.jar
            asset_content_type: application/java-archive
